# Generated by Django 4.0.3 on 2024-04-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='passwordcheack',
        ),
        migrations.AlterField(
            model_name='school',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
