# Generated by Django 4.0.3 on 2024-04-21 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='professor_lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_by_id_professor', to='myapp.course')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_by_name_professor', to='myapp.course', to_field='name')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='student_lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_by_id_student', to='myapp.course')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_by_name_student', to='myapp.course', to_field='name')),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.professor_lecture')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_1', models.CharField(max_length=1000, null=True)),
                ('problem_2', models.CharField(max_length=1000, null=True)),
                ('problem_3', models.CharField(max_length=1000, null=True)),
                ('problem_4', models.CharField(max_length=1000, null=True)),
                ('problem_5', models.CharField(max_length=1000, null=True)),
                ('problem_6', models.CharField(max_length=1000, null=True)),
                ('problem_7', models.CharField(max_length=1000, null=True)),
                ('problem_8', models.CharField(max_length=1000, null=True)),
                ('problem_9', models.CharField(max_length=1000, null=True)),
                ('problem_10', models.CharField(max_length=1000, null=True)),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.professor_lecture')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.CharField(max_length=1000, null=True)),
                ('answer_2', models.CharField(max_length=1000, null=True)),
                ('answer_3', models.CharField(max_length=1000, null=True)),
                ('answer_4', models.CharField(max_length=1000, null=True)),
                ('answer_5', models.CharField(max_length=1000, null=True)),
                ('answer_6', models.CharField(max_length=1000, null=True)),
                ('answer_7', models.CharField(max_length=1000, null=True)),
                ('answer_8', models.CharField(max_length=1000, null=True)),
                ('answer_9', models.CharField(max_length=1000, null=True)),
                ('answer_10', models.CharField(max_length=1000, null=True)),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.professor_lecture')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
