# Generated by Django 4.0.3 on 2024-04-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30)),
                ('lecture_id', models.CharField(max_length=30)),
                ('answer_1', models.CharField(max_length=1000, null=True)),
                ('answer_2', models.CharField(max_length=1000, null=True)),
                ('answer_3', models.CharField(max_length=1000, null=True)),
                ('answer_4', models.CharField(max_length=1000, null=True)),
                ('answer_5', models.CharField(max_length=1000, null=True)),
                ('answer_6', models.CharField(max_length=1000, null=True)),
                ('answer_7', models.CharField(max_length=1000, null=True)),
                ('answer_8', models.CharField(max_length=1000, null=True)),
                ('answer_9', models.CharField(max_length=1000, null=True)),
                ('answer_10', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(max_length=30)),
                ('lecture_id', models.CharField(max_length=30)),
                ('problem_1', models.CharField(max_length=1000, null=True)),
                ('problem_2', models.CharField(max_length=1000, null=True)),
                ('problem_3', models.CharField(max_length=1000, null=True)),
                ('problem_4', models.CharField(max_length=1000, null=True)),
                ('problem_5', models.CharField(max_length=1000, null=True)),
                ('problem_6', models.CharField(max_length=1000, null=True)),
                ('problem_7', models.CharField(max_length=1000, null=True)),
                ('problem_8', models.CharField(max_length=1000, null=True)),
                ('problem_9', models.CharField(max_length=1000, null=True)),
                ('problem_10', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='professor_lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=30)),
                ('course_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student_lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=30)),
                ('course_id', models.CharField(max_length=30)),
                ('lecture_id', models.CharField(max_length=30)),
            ],
        ),
    ]
